### ISSUE TITLE
Create a Task to install/upgrade Chocolatey itself

### ISSUE THREAD

**Issue by gep13** [chocolatey-community/chocolatey-azuredevops#13]
Similar to the NuGet Tool Installer Task

**Comment by gep13** [comment]
@flcdrg is this something that you wanted to tackle?  I think it would make sense to have this function in a single Azure DevOps extension, just as a separate task.

Happy to add you as a maintainer of this repository to allow you to help out with it.

**Comment by flcdrg** [comment]
I'll take a shot at it

**Comment by gep13** [comment]
@flcdrg I have invited you to become a maintainer of this repository, let me know if you didn't get the invite.

Are there any other changes/features you would like to see added to this before we ship a new release?

**Comment by flcdrg** [comment]
No, i'm good 😃
