### ISSUE TITLE
Deprecation warning when running the task

### ISSUE THREAD

**Issue by devedse** [chocolatey-community/chocolatey-azuredevops#51]
Whenever the task executes in a build the following deprecation warning is shown:

```
##[warning]Task 'ChocolateyInstaller' (1.1.1) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib
```

![image](https://user-images.githubusercontent.com/2350015/71668309-a8cbd200-2d68-11ea-99ff-a0973f24cba3.png)

**Comment by gep13** [comment]
@devedse thanks for reaching out, however, I believe that this issue has been opened on the wrong repository.  Based on the output you are showing you are using this extension:

https://marketplace.visualstudio.com/items?itemName=jungeriusit.jungit-choco

Not the one in this repository.
