### ISSUE TITLE
Install Chocolatey Task fails

### ISSUE THREAD

**Issue by kellyelton** [chocolatey-community/chocolatey-azuredevops#61]
Running the task throws the error `Cannot bind argument to parameter 'Path' because it is null.`

## Expected Behavior
Chocolatey should have installed cleanly.

## Current Behavior
Error is thrown.

## Steps to Reproduce (for bugs)
1. Install latest Azure DevOps server locally
2. Create a project and a build pipeline
3.  Add the 'Chocolatey Installer`
4. Run the pipeline
5. Only output is the error `Cannot bind argument to parameter 'Path' because it is null.`

## Context
I'm trying to have Chocolatey install on the build machine during a build.

## Your Environment
Latest Chocolatey extension gep13.chocolatey-azuredevops
Windows server 2019 datacenter 1809
Azure DevOps server 20198 17.143.28621.4

**Comment by flcdrg** [comment]
Thanks for the report. We've tested this with Azure DevOps service, so sounds like there's some assumptions we're making in the code that don't hold true for on-prem.
